feat(web): implement auth flow with protected route
- The signin/up page take inspiration from shadcn's blocks `login-03`
  and `signup-03`.
- Introduce the usage of TanStack Form and Zod validation to enable
  dynamic client-side validation for the form input.
- tsconfig's `baseUrl` is deprecated in TS7.0 (error TS5101) unless we
  specified `ignoreDeprecations: "6.0"`. We don't want to ignore this
  for future-sake, so it is removed.